# Base image
FROM node:20

# Create app directory
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install

RUN npm install -g nodemon

# Copy source code
COPY . .

# Expose port
EXPOSE 3000

# # Start the app
# CMD ["npm", "start"]

# Start in dev mode
CMD ["npm", "run", "dev"]
