
services:
  app:
    image: dockerdemo-app
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    environment:
      - MONGO_URL=mongodb://mongo:27017/nodedb

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "2817:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
