version: "3.9"

services:
  app:
    image: dockerdemo-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/nodedb
    volumes:
      - .:/usr/src/app               
      - /usr/src/app/node_modules    
    command: npm run dev             
    restart: unless-stopped

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "2817:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
